FROM t4j/chainer:latest

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install python-opencv
RUN apt-get -y build-dep python-imaging
RUN apt-get -y install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev
RUN pip install Pillow

RUN mkdir -p /var/log/t4j/chainerapp
