FROM t4j/chainer:latest

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install python-opencv
RUN apt-get -y build-dep python-imaging
RUN apt-get -y install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev
RUN pip install Pillow

RUN mkdir -p /var/log/t4j/chainerapp

RUN mkdir -p /usr/local/share/OpenCV/haarcascades/
RUN cd /usr/local/share/OpenCV/haarcascades/ && \
    wget https://raw.githubusercontent.com/Itseez/opencv/master/data/haarcascades/haarcascade_frontalface_alt.xml