FROM ubuntu:14.04

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y wget
RUN apt-get install -y zip
RUN apt-get install -y python-pip python-dev

RUN pip install numpy

RUN cd /opt && wget https://github.com/pfnet/chainer/archive/master.zip && \
 unzip master.zip && \
 mv chainer-master chainer  && \
 rm -f master.zip  && \ 
 cd chainer && \
 python setup.py install
